mvn compile exec:java \
-Dexec.mainClass=com.axiom.pipeline.AxiomBatch \
-Dexec.cleanupDaemonThreads=false \
-Dexec.args=" \
--streaming=false \
--project=axiom-239308 \
--stagingLocation=gs://axiom-239308-test/temp/ \
--tempLocation=gs://axiom-239308-test/staging/ \
--quote=USDT \
--base=BSV \
--exchange=okex_spot \
--autoscalingAlgorithm=THROUGHPUT_BASED \
--inputDirectory=gs://axiom-239308-coldline/output/partitioned \
--outputDataset=aggregations \
--workerMachineType=n1-highmem-8 \
--numWorkers=2 \
--maxNumWorkers=30 \
--runner=DataflowRunner"
